openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'realmeet'
servers:
  - url: 'http://localhost:3000'

paths:
  /rooms:
    get:
      summary: 'Return rooms'
      operationId: listRooms
      tags:
        - room
      parameters:
        - name: id
          description: ID of the room
          in: query
          schema:
            type: integer
            format: int6
      responses:
        '200':
          description: OK`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Romm:
      description: The unique identifier of a spacecraft
      type: object
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []